#!/bin/bash


if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 3
fi

#whoami
lastModificationSeconds=$(date +%s -r $1)
currentSeconds=$(date +%s)

difference=$(($currentSeconds - $lastModificationSeconds))

#echo $difference

if [[ $difference -gt 84600 ]]; then
	printf "Old Backup dating $(date -r $1)"
	exit 2;
else 
	printf "Good Backup dating $(date -r $1)"
	exit 0;
fi

exit 3
